/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Leon_dp (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lighthouse-at-portal-crossroads-66006d9a3e93417fa52f2c588e7df924
Title: Lighthouse at portal crossroads
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

import islandScene from '../assets/3d/lighthouse-at-portal-crossroads.glb'

const Island = (props) =>  {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lighthouse_at_portal_crossroads.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[1.645, -95.833, 94.19]}
          rotation={[-Math.PI, 1.57, 0]}>
          <group
            name="e27d494cd76c4dd19426c7bf9852b6fafbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="land" position={[-281.582, -423.806, 7043.328]} scale={100}>
                  <mesh
                    name="land_facade_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_facade_1_0.geometry}
                    material={materials.facade_1}
                  />
                  <mesh
                    name="land_road_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_road_0.geometry}
                    material={materials.road}
                  />
                  <mesh
                    name="land_wood_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_wood_1_0.geometry}
                    material={materials.wood_1}
                  />
                  <mesh
                    name="land_metal_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_metal_1_0.geometry}
                    material={materials.metal_1}
                  />
                  <mesh
                    name="land_light_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_light_1_0.geometry}
                    material={materials.light_1}
                  />
                  <mesh
                    name="land_light_2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_light_2_0.geometry}
                    material={materials.light_2}
                  />
                  <mesh
                    name="land_wood_2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_wood_2_0.geometry}
                    material={materials.wood_2}
                  />
                  <mesh
                    name="land_ground_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_ground_0.geometry}
                    material={materials.ground}
                  />
                  <mesh
                    name="land_stone_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_stone_0.geometry}
                    material={materials.stone}
                  />
                  <mesh
                    name="land_rock_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_rock_0.geometry}
                    material={materials.rock}
                  />
                  <mesh
                    name="land_glade_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_glade_0.geometry}
                    material={materials.glade}
                  />
                  <mesh
                    name="land_dark_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_dark_0.geometry}
                    material={materials.dark}
                  />
                  <mesh
                    name="land_roof_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.land_roof_0.geometry}
                    material={materials.roof}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lighthouse_at_portal_crossroads.glb')

export default Island;